nuxt/typescript

examples/function-api/minimal/pages/index.vue
examples/object-api/minimal/pages/index.vue
package.json
packages/types/config/index.d.ts
packages/typescript-build/test/fixture/pages/index.vue
packages/typescript-build/test/fixture/pages/interface.vue

 fix: add missing configuration `dir` typings

---

packages/typescript-runtime/lib/args.js
packages/typescript-runtime/lib/resolve.js
packages/typescript-runtime/test/args.test.js

Refactor code to be fully compatible with `nuxt/cli` & `nuxt/cli-edge`

refactor: use @nuxt/cli options

---

docs/guide/setup.md
docs/migration.md
packages/types/config/index.d.ts

https://github.com/nuxt/nuxt.js/pull/6203

refactor: rename `devModules` to `buildModules`

---

packages/types/config/router.d.ts

fix(types): make NuxtRouteConfig.chunkNames optional and add chunkName

---

docs/migration.md

fixed a small grammatical error

fix typo in TS migration docs

---

packages/types/app/index.d.ts

base in context:
https://github.com/nuxt/nuxt.js/blob/3b9eddc22387b53c395851a3e4b87f677df17ef0/packages/vue-app/template/utils.js#L137

fix(types): add VueRouter base in Context

---

packages/types/config/cli.d.ts

I ... am so sorry.
:man_facepalming:

fix(types): remove erroneous color

---

docs/.vuepress/config.js
docs/cookbook/store.md

#61
Not perfect by any means, but hopefully a helpful first stab at it. Very open to edits, changes and best practice from others.

docs: add initial store cookbook

---

docs/.vuepress/config.js
docs/index.md
docs/ja/cookbook/components/index.md
docs/ja/cookbook/components/script.class-api.ts
docs/ja/cookbook/components/script.composition-api.ts
docs/ja/cookbook/components/script.options-api.ts
docs/ja/cookbook/components/template.html
docs/ja/cookbook/configuration.md
docs/ja/cookbook/middlewares.md
docs/ja/cookbook/modules.md
docs/ja/cookbook/plugins.md
docs/ja/cookbook/server-middlewares.md
docs/ja/cookbook/store.md
docs/ja/guide/index.md
docs/ja/guide/lint.md
docs/ja/guide/runtime.md
docs/ja/guide/setup.md
docs/ja/index.md
docs/ja/migration.md

Hi, Thank you for this documentation. I added japanese translation.

docs: support japanese language

---

docs/ja/guide/runtime.md

Hi, I fix a link in ja doc.
refs #163

docs: fix a link in ja doc

---

docs/ja/cookbook/configuration.md
docs/ja/cookbook/server-middlewares.md
docs/ja/guide/index.md
docs/ja/guide/lint.md
docs/ja/guide/runtime.md

Hi😸
I'm glad that the Japanese document was added.
I made minor corrections to the translation.

fix japanese document

---

docs/cookbook/store.md

PR has been merged https://github.com/championswimmer/vuex-module-decorators/pull/157

docs: request pollution issue has been fixed on vuex-module-decorators

---

docs/guide/runtime.md

Fix the invalid JSON, makes it easier for people to copy/paste

docs: fix package.json in runtime section

---

packages/types/config/build.d.ts

closes [#6691](https://github.com/nuxt/nuxt.js/issues/6691)

fix: add babel preset types for function argument

---

docs/cookbook/store.md

docs: add example of vuex usage with modules

---

docs/.vuepress/config.js
docs/cookbook/store.md
docs/es/cookbook/components/index.md
docs/es/cookbook/components/script.class-api.ts
docs/es/cookbook/components/script.composition-api.ts
docs/es/cookbook/components/script.options-api.ts
docs/es/cookbook/components/template.html
docs/es/cookbook/configuration.md
docs/es/cookbook/middlewares.md
docs/es/cookbook/modules.md
docs/es/cookbook/plugins.md
docs/es/cookbook/server-middlewares.md
docs/es/cookbook/store.md
docs/es/guide/index.md
docs/es/guide/lint.md
docs/es/guide/runtime.md
docs/es/guide/setup.md
docs/es/index.md
docs/es/migration.md
docs/package-lock.json

I think have some typos with the accent in some letters, i hope the spanish community help me with this

docs(es): basic spanish translation

---

README.md

Three commits to pick a badge :man_facepalming:

chore: fix ci/cd badge

---

docs/.vuepress/config.js
docs/es/cookbook/components/index.md
docs/es/cookbook/configuration.md
docs/es/cookbook/modules.md
docs/es/cookbook/server-middlewares.md
docs/es/guide/index.md
docs/es/guide/runtime.md
docs/es/index.md
docs/es/migration.md

* docs(es): translated to spanish guides and index
* docs(es): translated to spanish cookbooks and migration guide
* docs(es): fix merge leftovers
* docs(es): fix translation reverted to english

docs: full translation to spanish

---

docs/.vuepress/config.js
docs/es/cookbook/components/index.md
docs/es/cookbook/components/script.class-api.ts
docs/es/cookbook/components/script.composition-api.ts
docs/es/cookbook/components/script.options-api.ts
docs/es/cookbook/components/template.html
docs/es/cookbook/configuration.md
docs/es/cookbook/middlewares.md
docs/es/cookbook/modules.md
docs/es/cookbook/plugins.md
docs/es/cookbook/server-middlewares.md
docs/es/cookbook/store.md
docs/es/guide/index.md
docs/es/guide/lint.md
docs/es/guide/runtime.md
docs/es/guide/setup.md
docs/es/index.md
docs/es/migration.md
docs/package-lock.json

Thanks to @MrJmpl3 & @jefer590

docs(es): add spanish translation

---

examples/class-api/minimal/nuxt.config.js
examples/composition-api/minimal/nuxt.config.js
examples/options-api/minimal/nuxt.config.js

latest recommendation is to use "buildModules"

Update nuxt.config.js in examples

---

packages/types/app/index.d.ts

Checked this in my app. Unfortunately, I could not find this in the source code.

fix(types): the refresh method returns a promise

---

packages/types/app/vue.d.ts

fix(types): add watchQuery function type

---

docs/ja/cookbook/middlewares.md
docs/ja/cookbook/store.md
docs/ja/guide/setup.md

Hi, I added following en document updates to Japanese documents.
+ 826234b
+ #212 and #270

docs(ja): add en updates to Japanese document

---

docs/ja/guide/lint.md

I corrected the translation a little.

docs(ja): fix translation

---

docs/guide/setup.md

Preview: https://deploy-preview-305--nuxt-typescript.netlify.com/guide/setup.html#configuration
Closes #303.

Add type declaration file tip in the documentation

---

docs/ja/guide/setup.md

Add Japanese translation for #305

docs(ja): add translation

---

docs/.vuepress/config.js
docs/guide/runtime.md
docs/zh-Hans/cookbook/components/index.md
docs/zh-Hans/cookbook/configuration.md
docs/zh-Hans/cookbook/middlewares.md
docs/zh-Hans/cookbook/modules.md
docs/zh-Hans/cookbook/plugins.md
docs/zh-Hans/cookbook/server-middlewares.md
docs/zh-Hans/cookbook/store.md
docs/zh-Hans/guide/index.md
docs/zh-Hans/guide/lint.md
docs/zh-Hans/guide/runtime.md
docs/zh-Hans/guide/setup.md
docs/zh-Hans/index.md

ported from zh-Hant translation, with some wording difference

docs(zh-Hans): Added Simplified Chinese translation

---

docs/cookbook/store.md
docs/es/cookbook/plugins.md
docs/es/cookbook/store.md
docs/es/guide/lint.md
docs/es/guide/runtime.md
docs/es/guide/setup.md

For Hackoctober, I update the docs of spanish.
Any typo, please comment to fix.

docs: update spanish

---

examples/class-api/minimal/package.json

fix(examples): add `vue-class-component` dependency

---

.eslintignore
.github/workflows/test.yml
docs/components/global/InjectCode.vue
docs/package.json
docs/plugins/vue-tabs.js
docs/yarn.lock
jest.config.js
package.json
packages/typescript-build/package.json
packages/typescript-build/src/index.ts
packages/typescript-runtime/package.json
yarn.lock

Closes #450 
Closes #454 
Closes #459 
Closes #460 
Closes #462 
Closes #466

chore(deps): upgrade dependencies (includes TypeScript 4.1)

---

package.json
packages/typescript-build/package.json
packages/typescript-runtime/package.json
yarn.lock

Closes #487 
Closes #488 
Closes #489

chore(deps): upgrade to typescript 4.2

---

docs/content/pt/cookbook/plugins.md

Fixing some typos from the latest fix.

docs(pt): fix some typos in portuguese translation

---

docs/content/en/guide/setup.md
docs/content/es/guide/setup.md
docs/content/ja/guide/setup.md
docs/content/pt/guide/setup.md
docs/content/shared/tsconfig.json.md
docs/content/zh-Hans/guide/setup.md
docs/content/zh-Hant/guide/setup.md

docs: fix example on how to configure `loaders`

---

docs/content/shared/tsconfig.json.md

added a missing comma in tsconfig.json.md

fix(docs): add missing trailing comma in tsconfig.json.md
