nuxt/typescript

- docs/guide/runtime.md
Hey there, great work on Nuxt 2.9!
I just noticed a little typo while migrating from 2.8 to 2.9:
```bash
yarn @nuxt/typescript-runtime
```
Should be:
```bash
yarn add @nuxt/typescript-runtime
```
> docs: add missing `add` argument

- packages/typescript-runtime/lib/args.js
Could not generate with `nuxt-ts generate`:
```bash
⨯ Unable to compile TypeScript:                                                                20:05:55
error TS5058: The specified path does not exist: '~.../generate/tsconfig.json'.
error TS5058: The specified path does not exist: 'generate/tsconfig.json'.
```
Adding `generate` to the cli option fixes it 👍
> fix(runtime): add missing generate cli option

- packages/typescript-runtime/lib/resolve.js
This PR fixes SyntaxError when node v8.
In Node8, typescript-runtime/lib/resolve.js throws `SyntaxError: Unexpected token` (see below).
Because node8 doesn't support [optional catch binding](https://github.com/tc39/proposal-optional-catch-binding). It is a part of es2019.
```
~~~~/node_modules/@nuxt/typescript-runtime/lib/resolve.js:6
} catch {
^
SyntaxError: Unexpected token {
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Module.require (module.js:597:17)
at require (internal/module.js:11:18)
at Object.<anonymous> …
```
> fix(runtime): fix SyntaxError when node v8

- docs/cookbook/components/script.function-api.ts
Fixed for Vue.js 2.x and Function API v2.2.0.
In practice, an undefined check of the `user` is also required but is omitted.
> Fix Function API cookbook

- docs/cookbook/plugins.md
III. Combined Inject import wrong Context from '@nuxt/types', It's should be { Plugin } ?
> docs: fix example in "Combined Inject" section

- packages/types/config/build.d.ts
Based on this line: https://github.com/nuxt/nuxt.js/blob/dev/packages/webpack/src/config/base.js#L359
For example, this code does not work now (type checking):
```ts
build: {
extractCSS: {
ignoreOrder: true
}
}
```
> fix(types): extractCSS accepts object value

- packages/types/package.json
- yarn.lock
`@types/chokidar` is deprecated and prints out the following message:
> This is a stub types definition. chokidar provides its own type definitions, so you do not need this installed.
There may be a reason I'm unaware of why this is still in the dependencies, but I think it can be removed.
> chore: remove stub deprecated @types/chokidar

- packages/types/index.d.ts
Documentation examples have this code for extending `NuxtAppOptions`:
```
declare module '@nuxt/types' {
interface NuxtAppOptions {
$myInjectedFunction(message: string): void
}
}
```
but that didn't work as `NuxtAppOptions` was not exported from
`types/index.d.ts`. So one had to either use `'@nuxt/types/app'`
module name or it wouldn't work.
For consistency with `Context`, I chose to export `NuxtAppOptions`.
> fix(types): update types to match documentation examples

- packages/typescript-build/lib/module.js
- packages/typescript-build/test/module.test.js
Resolves #76
```js
// nuxt.config.js
export default {
typescript: {
loaders: {
ts: {
// Use https://github.com/TypeStrong/ts-loader#options
},
tsx: {
// Use https://github.com/TypeStrong/ts-loader#options
}
}
}
}
```
> feat: ts-loader options

- packages/types/app/index.d.ts
- `$nuxt.refresh()`introduced in 2.9.0 [here](https://github.com/nuxt/nuxt.js/pull/6194)
- xxx introduced here / xxx implemented here
> fix(types): add missing typings for NuxtApp interface

- docs/cookbook/plugins.md
Since `inject` injects object also in Store, example should have
types extending the store.
> docs: add Store interface extend for combined inject

- packages/types/app/vue.d.ts
asyncData can be used to, for example decide if the page should
redirect or other things than returning a data object. Having no `void`
return type forces me to have a `return` statement at the end of function
body which looks weird and is unnecessary.
> fix(types): allow no return in asyncData

- packages/types/config/build.d.ts
For this purpose, I add { isModern } at  NuxtConfigurationBuild - filenames - ctx
> fix(types): add isModern type definition to build.filenames context

- packages/types/app/vue.d.ts
Add support for declaring the meta object in Nuxt.js Page, as we can see here https://github.com/nuxt/nuxt.js/tree/dev/examples/routes-meta 🤓 .
> fix(types): add typing for Routes meta

- packages/types/config/server-middleware.d.ts
This prefix is present in the documentation at https://nuxtjs.org/api/configuration-servermiddleware/ and in the code at https://github.com/nuxt/nuxt.js/blob/dev/packages/server/src/server.js#L202
> fix(types): Add prefix property to NuxtConfigurationServerMiddleware

- docs/ja/cookbook/store.md
I fixed the cookbook code of `vuex-module-decorators` in the Japanese documentation.
> docs(ja): fix store page

- packages/types/app/index.d.ts
https://nuxtjs.org/api/context#-code-from-code-a-href-https-router-vuejs-org-en-api-route-object-html-em-vue-router-route-em-a-
For using `from` route object in middleware, I added type in Context.
> fix: add `from` property in context interface

- packages/types/config/build.d.ts
- packages/types/package.json
- yarn.lock
Based on the documentation available here: https://nuxtjs.org/api/configuration-build/#loaders
**Notes:**
* Uses the packages' own types wherever possible, with `css-loader` and `vue-style-loader` being the notable exceptions.
* No types for [`stylus-loader`](https://www.npmjs.com/package/stylus-loader) - nor am I planning to do so.
* Adds vue-loader (which comes with its own types) to peerDependencies - is there a better way to do this?
> feat(types): add types for NuxtConfigurationLoaders

- packages/types/config/build.d.ts
Previous PR erroneously used `FileLoaderOptions` instead of `UrlLoaderOptions` for `fontUrl` and `imgUrl` loaders. This fixes it.
Closes #221
> fix(types): add correct url-loader options

- packages/types/config/server-middleware.d.ts
closes #183
(if you haven't already been working on this)
> fix(types): use connect type for server middleware

- docs/guide/lint.md
In the previous steps (Setup and Runtime), the yarn command is given first. However, for the Lint step, it is the opposite. Having the commands in the same order across the steps would give a more consistent experience.
> docs: reorder yarn command to be before npm command

- docs/guide/runtime.md
- docs/guide/setup.md
1. Add warning to ensure to await Nuxt readiness - to ensure `@nuxt/typescript-build` is loaded before proceeding. It seems simple enough that I'm not sure we need a cookbook or more extended example - just works out-of-the-box if you do this.
2. Add example of how to use with TS config, locale modules or serverMiddleware - along with a warning that this is unsupported and for advanced users only.
closes #219, #193, #154, #139
> docs: add warning for programmatic usage

- docs/guide/setup.md
> docs: add information on adding vue-shim.d.ts

- docs/ja/guide/lint.md
- docs/ja/guide/runtime.md
- docs/ja/guide/setup.md
I added en document updates (#210, #233, #234, #235) to Japanese documents.
> docs(ja): add en updates to Japanese document

- packages/types/app/index.d.ts
- packages/types/config/render.d.ts
connect now has it's own IncomingMessage class which inherits from http
and includes the originalUrl property. The request instances here are
coming from connect, so they should use this class.
The IncomingMessage class from connect was added in
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40776
> fix(types): use IncomingMessage from connect instead of from http

- docs/cookbook/store.md
Just a little reminder to add the axios-accessor plugin to nuxt.config.js (which I personally forgot about, losing ~2hours in the process).
> docs(cookbook/store): add reminder about axios accessor plugin

- packages/types/config/build.d.ts
UrlLoaderOptions should have `esModule` option, not `esModules`. Thanks @oppianmatt for finding this out!
Proof: https://github.com/webpack-contrib/url-loader#esmodule
> Mistake in @nuxt/types: should rename UrlLoaderOptions.esModules to esModule

- packages/typescript-build/package.json
- packages/typescript-build/test/module.test.ts
- yarn.lock
This commit includes renovate deps update and a fix for tests.
> Fix testing of fork-ts-checker-webpack-plugin v4

- packages/types/app/vue.d.ts
Those missing types breaks the whole typing of components in TS projects unfortunately.
I didn't see any "contribution guide" or anything. Hopefully I did things right 😅
> fix(types): adding fetchOnServer and fetchDelay missing types

- examples/composition-api/minimal/pages/index.vue
The composition-api example app is using `createComponent` in `pages/index.vue`.
`createComponent` has been deprecated and renamed to `defineComponent`.  See https://github.com/vuejs/vue-next/commit/1c4cdd841daa2ba9c1ec35068c92f1ae776cacea
This is a simple fix to the composition-api "basic" sandbox in Examples.
---
I wasn't sure where else to ask this.
I would like to contribute an "advanced" example Nuxt app that contains full typescript support and testing with the composition API.  It would be a more generic version of my recent project: https://github.com/ShaggyTech/vin-decoder 
I use that as an example only to show that's it's possible to use typescript, jest and the composition-api together nicely.  I've really enjoyed the smooth development experience once project setup and …
> fix(examples): use defineComponent in composition-api basic example

- packages/types/config/build.d.ts
Under some condition may return `undefined` to skip exclude list
```typescript
build: {
transpile: [
({ isDev, isClient }) => (!isDev && isClient && 'autotrack') || undefined,
],
},
```
Only transplie when is not `isDev` && `isClient`
> fix(types): fix build.transpile type

- tsconfig.json
Resolving recent cjs/jest issues as if we mock or disable esm, we cannot use typescript-build anymore for fixtures
> fix(pkg): use commonjs export

- docs/cookbook/store.md
we forgot to put async and await in the store docs.
Wouldn't it be better to write?
> add async and await to store docs

- docs/cookbook/plugins.md
- docs/es/cookbook/plugins.md
- docs/ja/cookbook/plugins.md
- docs/pt/cookbook/plugins.md
- docs/zh-Hant/cookbook/plugins.md
- prettier.config.js
**Add imports to avoid failure of type augmentation.**
Note that it's not necessary to import these specific modules - the mere fact of *any* import will do the trick, and may well be worth commenting in the docs. What do you think @kevinmarrec?
https://github.com/nuxt-community/composition-api/issues/178
> docs: import modules to be augmented

- docs/cookbook/plugins.md
When using `inject`, the value is also injected into `Context` ([source](https://github.com/nuxt/nuxt.js/blob/128c9743c40bf776af428e5ed36ea1a09a0ef7b8/packages/vue-app/template/index.js#L178)), so it should be covered in combined inject example.
> docs: update combined inject example

- docs/package.json
- docs/yarn.lock
- package.json
- packages/typescript-build/package.json
- packages/typescript-runtime/package.json
- yarn.lock
Closes #431 
Closes #433 
Closes #434 
Closes #435 
Closes #439 
**ts-node** upgrade dropped support for Node versions < 10, which will result in major bump of `@nuxt/typescript-runtime`.
> chore: upgrade to typescript 4

- docs/content/en/guide/setup.md
The [guide](https://typescript.nuxtjs.org/guide/setup/) leads to [a 404](https://typescript.nuxtjs.org/guide/cookbook/components/), but instead should point [here](https://typescript.nuxtjs.org/cookbook/components/). Removing the `/guide` will fix the link.
I'm not sure how you parse this file (the header at the markdown beginning irritates me) and I didn't test this locally. If the change is wrong, at least it's kind of a bug report :sweat_smile:
> corrected cookbook link

- packages/typescript-build/src/index.ts
By using the Nuxt's resolver, it was resolving to whatever version of the package `fork-ts-checker-webpack-plugin` npm or yarn would find. That happened because `@nuxt/core` (the package where the Nuxt's resolver is located) doesn't have `fork-ts-checker-webpack-plugin` as a declared dependency. The version installed by `@nuxt/typescript-build` wouldn't always be used if for instance another version of the dependency is also installed on the project.
This fixes #145.
> fix(typescript-build): wrong path for dependency

- docs/content/en/cookbook/modules.md
Signed-off-by: Ayush P Gupta <ayushpguptaapg@gmail.com>
This PR aims at adding missing relevant docs link to modules page.
Although this is bare minimum needed, but i think we should extend docs more.
Let me know the plans.
> chore: add modules docs link

- docs/content/en/guide/runtime.md
If you try to use `nuxt-ts`, you receive the following error.
```
IMPORTANT : Package deprecation
Nuxt TypeScript Support has been refactored to be used with nuxt package.
Which means that nuxt-ts package is now no longer needed and is now tagged as deprecated.
We highly recommend to follow the guidelines below :
Migration guide (2.5.x)
Using yarn
yarn remove nuxt-ts
yarn add nuxt
yarn add -D @nuxt/typescript
Using npm
npm uninstall nuxt-ts
npm install nuxt
npm install -D @nuxt/typescript
----- nuxt.config.ts ----- 
| build: {                 |
| -- useForkTsChecker: ... |
| ++ typescript : {        |
| ++   typeCheck: ...      |
| ++ }                     |
| }                        |
-------------------------- 
```
> docs: remove recommendation to use `nuxt-ts`

- docs/content/en/guide/lint.md
If you do not have ESLint installed, you will get the following error.
```
✖ Nuxt Fatal Error
Error: When you use 'eslint' option, make sure to install 'eslint'.
```
If we add this to the instructions, then users can avoid this error.
> docs: adds instruction for including ESLint

- renovate.json
Since `docs` is "impossible" to update to latest nuxt/docus, separate those out so that we can update other lock files.
Based on https://github.com/renovatebot/config-help/issues/89
> chore(deps): separate lock file updates per package.json

- packages/typescript-build/package.json
- packages/typescript-build/src/index.ts
User options were overwriting the defaults so it was not possible to override just some of the options.
> fix: deep merge user's module options

- packages/typescript-build/src/index.ts
Instead of passing whole Consola instance to `fork-ts-checker-webpack-plugin` options, which can't be serialized and would crash when trying to use JSON.serialize on it (see how it can happen in the linked issue), pass only an interface with required methods.
Our custom `consola` was not used AT ALL before this change. It was not set in the correct place so `fork-ts-checker-webpack-plugin` ignored it completely and just logged errors using `console` API. So this is also fixed now, in addition to fixing the crash.
Fixes #504
> fix(typescript-build): set logger instance correctly

- package.json
- packages/typescript-build/package.json
- packages/typescript-runtime/package.json
- yarn.lock
After quick look there doesn't seem to be any apparent issues with TypeScript 5 so allow it in the peer dependency range.
Given that TypeScript doesn't really follow semantic versioning rules, it can break at any point but I still think that this is better approach then having to update this module on each TypeScript release. If new TS version breaks this module then we can restrict or fix it then.
> fix: extend typescript peer dependency range to include 5.x

- docs/content/en/guide/setup.md
- docs/content/es/guide/setup.md
- docs/content/ja/guide/setup.md
- docs/content/pt/guide/setup.md
- docs/content/zh-Hans/guide/setup.md
- docs/content/zh-Hant/guide/setup.md
typo/self explanatory, 'import type' declarations can only be used in TypeScript files.
> fix(docs): change 'nuxt.config.js' to 'nuxt.config.ts'

- package.json
- packages/typescript-build/package.json
- packages/typescript-runtime/package.json
- renovate.json
- yarn.lock
`@nuxtjs` renovate config [uses `"rangeStrategy": "bump"`](https://github.com/nuxt/renovate-config-nuxt/blob/40e1aa96888eccbcf2e5479a02f190b0910f9b1c/package.json#L36) which is not ideal for modules as it bumps range of `dependencies` which is more likely to result in duplicate copies of that dependency when Nuxt or other packages also depend on those.
With `"rangeStategy": "auto"`, [renovate will](https://docs.renovatebot.com/configuration-options/#rangestrategy) bump pinned dependencies but not range dependencies. This is more sane behavior for modules IMO.
Change to "auto" and update `package.json`s so that dependencies specific to this module and `devDependencies` are pinned and dependencies that are shared have wider ranges.
> chore(deps): use rangeStrategy "auto" for renovate

- docs/content/en/guide/setup.md
- Clarify that `script setup` typechecking does not work
- Clarify that `typeCheck` options are merged and add info about supported and default values
Fixes #545
Fixes #593
> docs: add extra information about options handling
